### ISSUE TITLE
GHC 7.10 support?

### ISSUE THREAD

**Issue by wayofthepie** [ondrap/nats-queue#2]
I work solely on ghc 7.10 and it would be great to get nats-queue to compile on it. 

Yesterday the dequeue package was patched (0.1.7) so it would compile on 7.10, unfortunately this breaks compilation on 7.8.4, due to its use of length from Data.Foldable which did not exist back then.

I implemented changes [here](https://github.com/ondrap/nats-queue/compare/master...wayofthepie:ghc-7.10) which will allow nats-queue to compile on ghc 7.10. However, given the dequeue changes mentioned above, I can't see this working on 7.8.4 any more. 

I'd love to get those changes (or any changes for 7.10 support) merged and pushed to hackage. Is this something that can be done or do you want to keep supporting 7.8?

Thanks!

**Comment by ondrap** [comment]
Ok. No problem - I think we should do base >= 4.8, aeson >= 0.7 in the .cabal file. Could you add that and prepare a pull request?

**Comment by ondrap** [comment]
And obviously deque >= 0.1.7 too.

**Comment by wayofthepie** [comment]
Ok I can do that. 

One thing, base < 4.8 is a transitive dependency of all aeson libraries until 0.8.0.1 (directly because of the time library), so setting aeson >= 0.8.0.1 would be clearer I think - thoughts?

**Comment by ondrap** [comment]
I took your pull request and it seems to work. I will release a new version to hackage. BTW: I don't use this library, so if you thought you would like to take over the maintenance, I would certainly not object.

**Comment by wayofthepie** [comment]
Thanks for the release! I plan on integrating nats with a few projects so I would gladly take over maintenance.

**Comment by ondrap** [comment]
Ok, what's your hackage username? I will add you to the list of the maintainers for the package.

**Comment by wayofthepie** [comment]
It's **wayofthepie**. Thanks!

**Comment by ondrap** [comment]
Added, I think that's all what is needed. BTW: hackage doesn't like the constraint on the 'base' package, but it compiles for me...

**Comment by wayofthepie** [comment]
Strange! It compiles fine for me too.
